# Generated by Django 4.1.5 on 2023-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authflowapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='salt',
            field=models.CharField(default='asdasda', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
