# Generated by Django 4.1.5 on 2023-02-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authflowapi', '0003_alter_usermodel_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='usermodel',
            unique_together={('username', 'email')},
        ),
    ]
