# Generated by Django 4.1.5 on 2023-02-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authflowapi', '0004_alter_usermodel_email_alter_usermodel_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('access', models.BooleanField(default=False, verbose_name='Access')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
            ],
            options={
                'verbose_name': 'Permission',
            },
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterUniqueTogether(
            name='usermodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Username'),
        ),
    ]
