# Generated by Django 4.1.5 on 2023-02-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authflowapi', '0007_alter_permissionmodel_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionmodel',
            name='access',
        ),
        migrations.RemoveField(
            model_name='permissionmodel',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='permissionmodel',
            name='read',
        ),
    ]
