# Generated by Django 4.1.5 on 2023-02-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authflowapi', '0009_rolemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodel',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authflowapi.permissionmodel'),
        ),
    ]
